### PR TITLE
Initial commit for Business Rules UI

### PR DESCRIPTION
**Pull request by kylembischof**

### CODE REVIEW

**Comment by amosfong** [comment]
merged, thanks!

-Renamed stuff
A trigger would describe event + conditions being true. The action isn't part of the trigger so I think the whole thing should be called a "rule". We can use trigger within the rule for that section if we want though.

Let's use a different word for automations if we need it. But I think it can be handled in the regular rules if we have an event called "ongoing" or "continuous" or something. And I think all the same conditions apply to both types of rules?

**Comment by kylembischof** [comment]
That makes sense.

Yeah I was thinking separate them, since other systems call time based things automations and people might be used to that word and know what it is, but if you wanna include it in the rules and just have events called something relating to time, that would work too.

**Comment by amosfong** [comment]
oh, is automations a common term for this kind of thing?

**Comment by kylembischof** [comment]
yeah ive seen the term automation used on other systems for things like this too. maybe automations can be our term for encompassing all the rules? Maybe it would make it easier to understand what rules is actually for (to automate stuff)

**Comment by amosfong** [comment]
ah ok, yea I would put automation above rules then. And if needed have a different "type" or rule for the time based stuff.

**Pull request closed without merging**
